import React from 'react'
import ReactDOM from "react-dom";

class Table_covid extends React.Component {
    render() {
        return (
            <div className="table-responsive">
                <table className="table table-striped table-hover w-auto" >
                    <tbody className="text-right">
                        <tr classname="heading ">
                            <td className="text-left px-2 pt-4">State/UT</ td>
                            < td className=" px-2 pt-4">Confirmed</ td>
                            < td className="px-2 pt-4">Active</ td>
                            < td className="px-2 pt-4">Recovered</ td>
                            < td className="px-2 pt-4">Deceased</ td>
                            < td className="px-2 pt-4">Other</ td>
                            < td className="px-2 pt-4">Tested</ td>
                            < td className="px-2 pt-4">Vaccine Doses Administered</ td>
                            < td className="px-2 pt-4">Test Positivity Ratio</ td>
                            < td className="px-2 pt-4">Case Fatality Ratio</ td>
                            < td className="px-2 pt-4">Recovery Ratio</ td>
                            < td className="px-2 pt-4">Active Ratio</ td>
                            < td className="px-2 pt-4">Population</ td>
                        </tr>
                        <tr className="state_Maharashtra">
                            <td className="Maharashtra table-active text-left p-2">Maharashtra</ td>
                            < td className="Maharashtra p-2">Confirmed</ td>
                            < td className="Maharashtra p-2">Active</ td>
                            < td className="Maharashtra p-2">Recovered</ td>
                            < td className="Maharashtra p-2">Deceased</ td>
                            < td className="Maharashtra p-2">Other</ td>
                            < td className="Maharashtra p-2">Tested</ td>
                            < td className="Maharashtra p-2">Vaccine Doses Administered</ td>
                            < td className="Maharashtra p-2">Test Positivity Ratio</ td>
                            < td className="Maharashtra p-2">Case Fatality Ratio</ td>
                            < td className="Maharashtra p-2">Recovery Ratio</ td>
                            < td className="Maharashtra p-2">Active Ratio</ td>
                            < td className="Maharashtra p-2">Population</ td>
                        </tr>
                        <tr className="state_Karnataka">
                            <td className="Karnataka table-default text-left p-2">Karnataka</ td>
                            < td className="Karnataka p-2">Confirmed</ td>
                            < td className="Karnataka p-2">Active</ td>
                            < td className="Karnataka p-2">Recovered</ td>
                            < td className="Karnataka p-2">Deceased</ td>
                            < td className="Karnataka p-2">Other</ td>
                            < td className="Karnataka p-2">Tested</ td>
                            < td className="Karnataka p-2">Vaccine Doses Administered</ td>
                            < td className="Karnataka p-2">Test Positivity Ratio</ td>
                            < td className="Karnataka p-2">Case Fatality Ratio</ td>
                            < td className="Karnataka p-2">Recovery Ratio</ td>
                            < td className="Karnataka p-2">Active Ratio</ td>
                            < td className="Karnataka p-2">Population</ td>
                        </tr>
                        <tr className="state_Kerala">
                            <td className="Kerala table-active text-left p-2">Kerala</ td>
                            < td className="Kerala p-2">Confirmed</ td>
                            < td className="Kerala p-2">Active</ td>
                            < td className="Kerala p-2">Recovered</ td>
                            < td className="Kerala p-2">Deceased</ td>
                            < td className="Kerala p-2">Other</ td>
                            < td className="Kerala p-2">Tested</ td>
                            < td className="Kerala p-2">Vaccine Doses Administered</ td>
                            < td className="Kerala p-2">Test Positivity Ratio</ td>
                            < td className="Kerala p-2">Case Fatality Ratio</ td>
                            < td className="Kerala p-2">Recovery Ratio</ td>
                            < td className="Kerala p-2">Active Ratio</ td>
                            < td className="Kerala p-2">Population</ td>
                        </tr>
                        <tr className="state_UttarPradesh">
                            <td className="UttarPradesh table-default text-left p-2">Uttar Pradesh</ td>
                            < td className="UttarPradesh p-2">Confirmed</ td>
                            < td className="UttarPradesh p-2">Active</ td>
                            < td className="UttarPradesh p-2">Recovered</ td>
                            < td className="UttarPradesh p-2">Deceased</ td>
                            < td className="UttarPradesh p-2">Other</ td>
                            < td className="UttarPradesh p-2">Tested</ td>
                            < td className="UttarPradesh p-2">Vaccine Doses Administered</ td>
                            < td className="UttarPradesh p-2">Test Positivity Ratio</ td>
                            < td className="UttarPradesh p-2">Case Fatality Ratio</ td>
                            < td className="UttarPradesh p-2">Recovery Ratio</ td>
                            < td className="UttarPradesh p-2">Active Ratio</ td>
                            < td className="UttarPradesh p-2">Population</ td>
                        </tr>
                        <tr className="state_TamilNadu">
                            <td className="TamilNadu table-active text-left p-2">Tamil Nadu</ td>
                            < td className="TamilNadu p-2">Confirmed</ td>
                            < td className="TamilNadu p-2">Active</ td>
                            < td className="TamilNadu p-2">Recovered</ td>
                            < td className="TamilNadu p-2">Deceased</ td>
                            < td className="TamilNadu p-2">Other</ td>
                            < td className="TamilNadu p-2">Tested</ td>
                            < td className="TamilNadu p-2">Vaccine Doses Administered</ td>
                            < td className="TamilNadu p-2">Test Positivity Ratio</ td>
                            < td className="TamilNadu p-2">Case Fatality Ratio</ td>
                            < td className="TamilNadu p-2">Recovery Ratio</ td>
                            < td className="TamilNadu p-2">Active Ratio</ td>
                            < td className="TamilNadu p-2">Population</ td>
                        </tr>
                        <tr className="state_Delhi">
                            <td className="Delhi table-default text-left p-2">Delhi</ td>
                            < td className="Delhi p-2">Confirmed</ td>
                            < td className="Delhi p-2">Active</ td>
                            < td className="Delhi p-2">Recovered</ td>
                            < td className="Delhi p-2">Deceased</ td>
                            < td className="Delhi p-2">Other</ td>
                            < td className="Delhi p-2">Tested</ td>
                            < td className="Delhi p-2">Vaccine Doses Administered</ td>
                            < td className="Delhi p-2">Test Positivity Ratio</ td>
                            < td className="Delhi p-2">Case Fatality Ratio</ td>
                            < td className="Delhi p-2">Recovery Ratio</ td>
                            < td className="Delhi p-2">Active Ratio</ td>
                            < td className="Delhi p-2">Population</ td>
                        </tr>
                        <tr className="state_AndhraPradesh">
                            <td className="AndhraPradesh table-active text-left p-2">Andhra Pradesh</ td>
                            < td className="AndhraPradesh p-2" >Confirmed</ td>
                            < td className="AndhraPradesh p-2" >Active</ td>
                            < td className="AndhraPradesh p-2" >Recovered</ td>
                            < td className="AndhraPradesh p-2" >Deceased</ td>
                            < td className="AndhraPradesh p-2" >Other</ td>
                            < td className="AndhraPradesh p-2" >Tested</ td>
                            < td className="AndhraPradesh p-2" >Vaccine Doses Administered</ td>
                            < td className="AndhraPradesh p-2" >Test Positivity Ratio</ td>
                            < td className="AndhraPradesh p-2" >Case Fatality Ratio</ td>
                            < td className="AndhraPradesh p-2" >Recovery Ratio</ td>
                            < td className="AndhraPradesh p-2" >Active Ratio</ td>
                            < td className="AndhraPradesh p-2" >Population</ td>
                        </tr>
                        <tr className="state_WestBengal">
                            <td className="WestBengal table-default text-left p-2">West Bengal</ td>
                            < td className="WestBengal p-2" >Confirmed</ td>
                            < td className="WestBengal p-2" >Active</ td>
                            < td className="WestBengal p-2" >Recovered</ td>
                            < td className="WestBengal p-2" >Deceased</ td>
                            < td className="WestBengal p-2" >Other</ td>
                            < td className="WestBengal p-2" >Tested</ td>
                            < td className="WestBengal p-2" >Vaccine Doses Administered</ td>
                            < td className="WestBengal p-2" >Test Positivity Ratio</ td>
                            < td className="WestBengal p-2" >Case Fatality Ratio</ td>
                            < td className="WestBengal p-2" >Recovery Ratio</ td>
                            < td className="WestBengal p-2" >Active Ratio</ td>
                            < td className="WestBengal p-2" >Population</ td>
                        </tr>
                        <tr className="state_Chhattisgarh">
                            <td className="Chhattisgarh table-active text-left p-2">Chhattisgarh</ td>
                            < td className="Chhattisgarh p-2" >Confirmed</ td>
                            < td className="Chhattisgarh p-2" >Active</ td>
                            < td className="Chhattisgarh p-2" >Recovered</ td>
                            < td className="Chhattisgarh p-2" >Deceased</ td>
                            < td className="Chhattisgarh p-2" >Other</ td>
                            < td className="Chhattisgarh p-2" >Tested</ td>
                            < td className="Chhattisgarh p-2" >Vaccine Doses Administered</ td>
                            < td className="Chhattisgarh p-2" >Test Positivity Ratio</ td>
                            < td className="Chhattisgarh p-2" >Case Fatality Ratio</ td>
                            < td className="Chhattisgarh p-2" >Recovery Ratio</ td>
                            < td className="Chhattisgarh p-2" >Active Ratio</ td>
                            < td className="Chhattisgarh p-2" >Population</ td>
                        </tr>
                        <tr className="state_Rajasthan">
                            <td className="Rajasthan table-default text-left p-2">Rajasthan</ td>
                            < td className="Rajasthan p-2">Confirmed</ td>
                            < td className="Rajasthan p-2">Active</ td>
                            < td className="Rajasthan p-2">Recovered</ td>
                            < td className="Rajasthan p-2">Deceased</ td>
                            < td className="Rajasthan p-2">Other</ td>
                            < td className="Rajasthan p-2">Tested</ td>
                            < td className="Rajasthan p-2">Vaccine Doses Administered</ td>
                            < td className="Rajasthan p-2">Test Positivity Ratio</ td>
                            < td className="Rajasthan p-2">Case Fatality Ratio</ td>
                            < td className="Rajasthan p-2">Recovery Ratio</ td>
                            < td className="Rajasthan p-2">Active Ratio</ td>
                            < td className="Rajasthan p-2">Population</ td>
                        </tr>
                        <tr className="state_Gujarat">
                            <td className="Gujarat table-active text-left p-2">Gujarat</ td>
                            < td className="Gujarat p-2">Confirmed</ td>
                            < td className="Gujarat p-2">Active</ td>
                            < td className="Gujarat p-2">Recovered</ td>
                            < td className="Gujarat p-2">Deceased</ td>
                            < td className="Gujarat p-2">Other</ td>
                            < td className="Gujarat p-2">Tested</ td>
                            < td className="Gujarat p-2">Vaccine Doses Administered</ td>
                            < td className="Gujarat p-2">Test Positivity Ratio</ td>
                            < td className="Gujarat p-2">Case Fatality Ratio</ td>
                            < td className="Gujarat p-2">Recovery Ratio</ td>
                            < td className="Gujarat p-2">Active Ratio</ td>
                            < td className="Gujarat p-2">Population</ td>
                        </tr>
                        <tr className="state_MadhyaPradesh">
                            <td className="MadhyaPradesh table-default text-left p-2">Madhya Pradesh</ td>
                            < td className="MadhyaPradesh p-2">Confirmed</ td>
                            < td className="MadhyaPradesh p-2">Active</ td>
                            < td className="MadhyaPradesh p-2">Recovered</ td>
                            < td className="MadhyaPradesh p-2">Deceased</ td>
                            < td className="MadhyaPradesh p-2">Other</ td>
                            < td className="MadhyaPradesh p-2">Tested</ td>
                            < td className="MadhyaPradesh p-2">Vaccine Doses Administered</ td>
                            < td className="MadhyaPradesh p-2">Test Positivity Ratio</ td>
                            < td className="MadhyaPradesh p-2">Case Fatality Ratio</ td>
                            < td className="MadhyaPradesh p-2">Recovery Ratio</ td>
                            < td className="MadhyaPradesh p-2">Active Ratio</ td>
                            < td className="MadhyaPradesh p-2">Population</ td>
                        </tr>
                        <tr className="state_Haryana">
                            <td className="Haryana table-active text-left p-2">Haryana</ td>
                            < td className="Haryana p-2" >Confirmed</ td>
                            < td className="Haryana p-2" >Active</ td>
                            < td className="Haryana p-2" >Recovered</ td>
                            < td className="Haryana p-2" >Deceased</ td>
                            < td className="Haryana p-2" >Other</ td>
                            < td className="Haryana p-2" >Tested</ td>
                            < td className="Haryana p-2" >Vaccine Doses Administered</ td>
                            < td className="Haryana p-2" >Test Positivity Ratio</ td>
                            < td className="Haryana p-2" >Case Fatality Ratio</ td>
                            < td className="Haryana p-2" >Recovery Ratio</ td>
                            < td className="Haryana p-2" >Active Ratio</ td>
                            < td className="Haryana p-2" >Population</ td>
                        </tr>
                        <tr className="state_Bihar">
                            <td className="Bihar table-default text-left p-2">Bihar</ td>
                            < td className="Bihar p-2">Confirmed</ td>
                            < td className="Bihar p-2">Active</ td>
                            < td className="Bihar p-2">Recovered</ td>
                            < td className="Bihar p-2">Deceased</ td>
                            < td className="Bihar p-2">Other</ td>
                            < td className="Bihar p-2">Tested</ td>
                            < td className="Bihar p-2">Vaccine Doses Administered</ td>
                            < td className="Bihar p-2">Test Positivity Ratio</ td>
                            < td className="Bihar p-2">Case Fatality Ratio</ td>
                            < td className="Bihar p-2">Recovery Ratio</ td>
                            < td className="Bihar p-2">Active Ratio</ td>
                            < td className="Bihar p-2">Population</ td>
                        </tr>
                        <tr className="state_Odisha">
                            <td className="Odisha table-active text-left p-2">Odisha</ td>
                            < td className="Odisha p-2">Confirmed</ td>
                            < td className="Odisha p-2">Active</ td>
                            < td className="Odisha p-2">Recovered</ td>
                            < td className="Odisha p-2">Deceased</ td>
                            < td className="Odisha p-2">Other</ td>
                            < td className="Odisha p-2">Tested</ td>
                            < td className="Odisha p-2">Vaccine Doses Administered</ td>
                            < td className="Odisha p-2">Test Positivity Ratio</ td>
                            < td className="Odisha p-2">Case Fatality Ratio</ td>
                            < td className="Odisha p-2">Recovery Ratio</ td>
                            < td className="Odisha p-2">Active Ratio</ td>
                            < td className="Odisha p-2">Population</ td>
                        </tr>
                        <tr className="state_Telangana">
                            <td className="Telangana table-default text-left p-2">Telangana</ td>
                            < td className="Telangana p-2">Confirmed</ td>
                            < td className="Telangana p-2">Active</ td>
                            < td className="Telangana p-2">Recovered</ td>
                            < td className="Telangana p-2">Deceased</ td>
                            < td className="Telangana p-2">Other</ td>
                            < td className="Telangana p-2">Tested</ td>
                            < td className="Telangana p-2">Vaccine Doses Administered</ td>
                            < td className="Telangana p-2">Test Positivity Ratio</ td>
                            < td className="Telangana p-2">Case Fatality Ratio</ td>
                            < td className="Telangana p-2">Recovery Ratio</ td>
                            < td className="Telangana p-2">Active Ratio</ td>
                            < td className="Telangana p-2">Population</ td>
                        </tr>
                        <tr className="state_Punjab">
                            <td className="Punjab table-active text-left p-2">Punjab</ td>
                            < td className="Punjab">Confirmed</ td>
                            < td className="Punjab">Active</ td>
                            < td className="Punjab">Recovered</ td>
                            < td className="Punjab">Deceased</ td>
                            < td className="Punjab">Other</ td>
                            < td className="Punjab">Tested</ td>
                            < td className="Punjab">Vaccine Doses Administered</ td>
                            < td className="Punjab">Test Positivity Ratio</ td>
                            < td className="Punjab">Case Fatality Ratio</ td>
                            < td className="Punjab">Recovery Ratio</ td>
                            < td className="Punjab">Active Ratio</ td>
                            < td className="Punjab">Population</ td>
                        </tr>
                        <tr className="state_Assam">
                            <td className="Assam table-default text-left p-2">Assam</ td>
                            < td className="Assam">Confirmed</ td>
                            < td className="Assam">Active</ td>
                            < td className="Assam">Recovered</ td>
                            < td className="Assam">Deceased</ td>
                            < td className="Assam">Other</ td>
                            < td className="Assam">Tested</ td>
                            < td className="Assam">Vaccine Doses Administered</ td>
                            < td className="Assam">Test Positivity Ratio</ td>
                            < td className="Assam">Case Fatality Ratio</ td>
                            < td className="Assam">Recovery Ratio</ td>
                            < td className="Assam">Active Ratio</ td>
                            < td className="Assam">Population</ td>
                        </tr>
                        <tr className="state_Jharkhand">
                            <td className="Jharkhand table-active text-left p-2">Jharkhand</ td>
                            < td className="Jharkhand p-2">Confirmed</ td>
                            < td className="Jharkhand p-2">Active</ td>
                            < td className="Jharkhand p-2">Recovered</ td>
                            < td className="Jharkhand p-2">Deceased</ td>
                            < td className="Jharkhand p-2">Other</ td>
                            < td className="Jharkhand p-2">Tested</ td>
                            < td className="Jharkhand p-2">Vaccine Doses Administered</ td>
                            < td className="Jharkhand p-2">Test Positivity Ratio</ td>
                            < td className="Jharkhand p-2">Case Fatality Ratio</ td>
                            < td className="Jharkhand p-2">Recovery Ratio</ td>
                            < td className="Jharkhand p-2">Active Ratio</ td>
                            < td className="Jharkhand p-2">Population</ td>
                        </tr>
                        <tr className="state_Uttarakhand">
                            <td className="Uttarakhand table-default text-left p-2">Uttarakhand</ td>
                            < td className="Uttarakhand p-2">Confirmed</ td>
                            < td className="Uttarakhand p-2">Active</ td>
                            < td className="Uttarakhand p-2">Recovered</ td>
                            < td className="Uttarakhand p-2">Deceased</ td>
                            < td className="Uttarakhand p-2">Other</ td>
                            < td className="Uttarakhand p-2">Tested</ td>
                            < td className="Uttarakhand p-2">Vaccine Doses Administered</ td>
                            < td className="Uttarakhand p-2">Test Positivity Ratio</ td>
                            < td className="Uttarakhand p-2">Case Fatality Ratio</ td>
                            < td className="Uttarakhand p-2">Recovery Ratio</ td>
                            < td className="Uttarakhand p-2">Active Ratio</ td>
                            < td className="Uttarakhand p-2">Population</ td>
                        </tr>
                        <tr className="state_jandK">
                            <td className="JandK table-active text-left p-2">Jammu and Kashmir</ td>
                            < td className="JandK p-2">Confirmed</ td>
                            < td className="JandK p-2">Active</ td>
                            < td className="JandK p-2">Recovered</ td>
                            < td className="JandK p-2">Deceased</ td>
                            < td className="JandK p-2">Other</ td>
                            < td className="JandK p-2">Tested</ td>
                            < td className="JandK p-2">Vaccine Doses Administered</ td>
                            < td className="JandK p-2">Test Positivity Ratio</ td>
                            < td className="JandK p-2">Case Fatality Ratio</ td>
                            < td className="JandK p-2">Recovery Ratio</ td>
                            < td className="JandK p-2">Active Ratio</ td>
                            < td className="JandK p-2">Population</ td>
                        </tr>
                        <tr className="state_HimachalPradesh">
                            <td className="HimachalPradesh table-default text-left p-2">Himachal Pradesh</ td>
                            < td className="HimachalPradesh p-2">Confirmed</ td>
                            < td className="HimachalPradesh p-2">Active</ td>
                            < td className="HimachalPradesh p-2">Recovered</ td>
                            < td className="HimachalPradesh p-2">Deceased</ td>
                            < td className="HimachalPradesh p-2">Other</ td>
                            < td className="HimachalPradesh p-2">Tested</ td>
                            < td className="HimachalPradesh p-2">Vaccine Doses Administered</ td>
                            < td className="HimachalPradesh p-2">Test Positivity Ratio</ td>
                            < td className="HimachalPradesh p-2">Case Fatality Ratio</ td>
                            < td className="HimachalPradesh p-2">Recovery Ratio</ td>
                            < td className="HimachalPradesh p-2">Active Ratio</ td>
                            < td className="HimachalPradesh p-2">Population</ td>
                        </tr>
                        <tr className="state_Goa">
                            <td className="Goa table-active text-left p-2">Goa</ td>
                            < td className="Goa p-2">Confirmed</ td>
                            < td className="Goa p-2">Active</ td>
                            < td className="Goa p-2">Recovered</ td>
                            < td className="Goa p-2">Deceased</ td>
                            < td className="Goa p-2">Other</ td>
                            < td className="Goa p-2">Tested</ td>
                            < td className="Goa p-2">Vaccine Doses Administered</ td>
                            < td className="Goa p-2">Test Positivity Ratio</ td>
                            < td className="Goa p-2">Case Fatality Ratio</ td>
                            < td className="Goa p-2">Recovery Ratio</ td>
                            < td className="Goa p-2">Active Ratio</ td>
                            < td className="Goa p-2">Population</ td>
                        </tr>
                        <tr className="state_Puducherry">
                            <td className="Puducherry table-default text-left p-2">Puducherry</ td>
                            < td className="Puducherry p-2">Confirmed</ td>
                            < td className="Puducherry p-2">Active</ td>
                            < td className="Puducherry p-2">Recovered</ td>
                            < td className="Puducherry p-2">Deceased</ td>
                            < td className="Puducherry p-2">Other</ td>
                            < td className="Puducherry p-2">Tested</ td>
                            < td className="Puducherry p-2">Vaccine Doses Administered</ td>
                            < td className="Puducherry p-2">Test Positivity Ratio</ td>
                            < td className="Puducherry p-2">Case Fatality Ratio</ td>
                            < td className="Puducherry p-2">Recovery Ratio</ td>
                            < td className="Puducherry p-2">Active Ratio</ td>
                            < td className="Puducherry p-2">Population</ td>
                        </tr>
                        <tr className="state_Chandigarh">
                            <td className="Chandigarh table-active text-left p-2">Chandigarh</ td>
                            < td className="Chandigarh p-2">Confirmed</ td>
                            < td className="Chandigarh p-2">Active</ td>
                            < td className="Chandigarh p-2">Recovered</ td>
                            < td className="Chandigarh p-2">Deceased</ td>
                            < td className="Chandigarh p-2">Other</ td>
                            < td className="Chandigarh p-2">Tested</ td>
                            < td className="Chandigarh p-2">Vaccine Doses Administered</ td>
                            < td className="Chandigarh p-2">Test Positivity Ratio</ td>
                            < td className="Chandigarh p-2">Case Fatality Ratio</ td>
                            < td className="Chandigarh p-2">Recovery Ratio</ td>
                            < td className="Chandigarh p-2">Active Ratio</ td>
                            < td className="Chandigarh p-2">Population</ td>
                        </tr>
                        <tr className="state_Tripura">
                            <td className="Tripura table-default text-left p-2">Tripura</ td>
                            < td className="Tripura p-2">Confirmed</ td>
                            < td className="Tripura p-2">Active</ td>
                            < td className="Tripura p-2">Recovered</ td>
                            < td className="Tripura p-2">Deceased</ td>
                            < td className="Tripura p-2">Other</ td>
                            < td className="Tripura p-2">Tested</ td>
                            < td className="Tripura p-2">Vaccine Doses Administered</ td>
                            < td className="Tripura p-2">Test Positivity Ratio</ td>
                            < td className="Tripura p-2">Case Fatality Ratio</ td>
                            < td className="Tripura p-2">Recovery Ratio</ td>
                            < td className="Tripura p-2">Active Ratio</ td>
                            < td className="Tripura p-2">Population</ td>
                        </tr>
                        <tr className="state_Manipur">
                            <td className="Manipur table-active text-left p-2">Manipur</ td>
                            < td className="Manipur p-2" >Confirmed</ td>
                            < td className="Manipur p-2" >Active</ td>
                            < td className="Manipur p-2" >Recovered</ td>
                            < td className="Manipur p-2" >Deceased</ td>
                            < td className="Manipur p-2" >Other</ td>
                            < td className="Manipur p-2" >Tested</ td>
                            < td className="Manipur p-2" >Vaccine Doses Administered</ td>
                            < td className="Manipur p-2" >Test Positivity Ratio</ td>
                            < td className="Manipur p-2" >Case Fatality Ratio</ td>
                            < td className="Manipur p-2" >Recovery Ratio</ td>
                            < td className="Manipur p-2" >Active Ratio</ td>
                            < td className="Manipur p-2" >Population</ td>
                        </tr>
                        <tr className="state_ArunachalPradesh">
                            <td className="ArunachalPradesh table-default text-left p-2">Arunachal Pradesh</ td>
                            < td className="ArunachalPradesh p-2">Confirmed</ td>
                            < td className="ArunachalPradesh p-2">Active</ td>
                            < td className="ArunachalPradesh p-2">Recovered</ td>
                            < td className="ArunachalPradesh p-2">Deceased</ td>
                            < td className="ArunachalPradesh p-2">Other</ td>
                            < td className="ArunachalPradesh p-2">Tested</ td>
                            < td className="ArunachalPradesh p-2">Vaccine Doses Administered</ td>
                            < td className="ArunachalPradesh p-2">Test Positivity Ratio</ td>
                            < td className="ArunachalPradesh p-2">Case Fatality Ratio</ td>
                            < td className="ArunachalPradesh p-2">Recovery Ratio</ td>
                            < td className="ArunachalPradesh p-2">Active Ratio</ td>
                            < td className="ArunachalPradesh p-2">Population</ td>
                        </tr>
                        <tr className="state_Meghalaya">
                            <td className="Meghalaya table-active text-left p-2">Meghalaya</ td>
                            < td className="Meghalaya p-2">Confirmed</ td>
                            < td className="Meghalaya p-2">Active</ td>
                            < td className="Meghalaya p-2">Recovered</ td>
                            < td className="Meghalaya p-2">Deceased</ td>
                            < td className="Meghalaya p-2">Other</ td>
                            < td className="Meghalaya p-2">Tested</ td>
                            < td className="Meghalaya p-2">Vaccine Doses Administered</ td>
                            < td className="Meghalaya p-2">Test Positivity Ratio</ td>
                            < td className="Meghalaya p-2">Case Fatality Ratio</ td>
                            < td className="Meghalaya p-2">Recovery Ratio</ td>
                            < td className="Meghalaya p-2">Active Ratio</ td>
                            < td className="Meghalaya p-2">Population</ td>
                        </tr>
                        <tr className="state_Nagaland">
                            <td className="Nagaland table-default text-left p-2">Nagaland</ td>
                            < td className="Nagaland p-2" >Confirmed</ td>
                            < td className="Nagaland p-2" >Active</ td>
                            < td className="Nagaland p-2" >Recovered</ td>
                            < td className="Nagaland p-2" >Deceased</ td>
                            < td className="Nagaland p-2" >Other</ td>
                            < td className="Nagaland p-2" >Tested</ td>
                            < td className="Nagaland p-2" >Vaccine Doses Administered</ td>
                            < td className="Nagaland p-2" >Test Positivity Ratio</ td>
                            < td className="Nagaland p-2" >Case Fatality Ratio</ td>
                            < td className="Nagaland p-2" >Recovery Ratio</ td>
                            < td className="Nagaland p-2" >Active Ratio</ td>
                            < td className="Nagaland p-2" >Population</ td>
                        </tr>
                        <tr className="state_Ladakh">
                            <td className="Ladakh p-2 table-active text-left">Ladakh</ td>
                            < td className="Ladakh p-2">Confirmed</ td>
                            < td className="Ladakh p-2">Active</ td>
                            < td className="Ladakh p-2">Recovered</ td>
                            < td className="Ladakh p-2">Deceased</ td>
                            < td className="Ladakh p-2">Other</ td>
                            < td className="Ladakh p-2">Tested</ td>
                            < td className="Ladakh p-2">Vaccine Doses Administered</ td>
                            < td className="Ladakh p-2">Test Positivity Ratio</ td>
                            < td className="Ladakh p-2">Case Fatality Ratio</ td>
                            < td className="Ladakh p-2">Recovery Ratio</ td>
                            < td className="Ladakh p-2">Active Ratio</ td>
                            < td className="Ladakh p-2">Population</ td>
                        </tr>
                        <tr className="state_Sikkim">
                            <td className="Sikkim p-2 table-default text-left">Sikkim</ td>
                            < td className="Sikkim p-2" >Confirmed</ td>
                            < td className="Sikkim p-2" >Active</ td>
                            < td className="Sikkim p-2" >Recovered</ td>
                            < td className="Sikkim p-2" >Deceased</ td>
                            < td className="Sikkim p-2" >Other</ td>
                            < td className="Sikkim p-2" >Tested</ td>
                            < td className="Sikkim p-2" >Vaccine Doses Administered</ td>
                            < td className="Sikkim p-2" >Test Positivity Ratio</ td>
                            < td className="Sikkim p-2" >Case Fatality Ratio</ td>
                            < td className="Sikkim p-2" >Recovery Ratio</ td>
                            < td className="Sikkim p-2" >Active Ratio</ td>
                            < td className="Sikkim p-2" >Population</ td>
                        </tr>
                        <tr className="state_Dadiu">
                            <td className="Dadiu p-2 table-active text-left">Dadra and Nagar Haveli and Daman and Diu</ td>
                            < td className="Dadiu p-2" >Confirmed</ td>
                            < td className="Dadiu p-2" >Active</ td>
                            < td className="Dadiu p-2" >Recovered</ td>
                            < td className="Dadiu p-2" >Deceased</ td>
                            < td className="Dadiu p-2" >Other</ td>
                            < td className="Dadiu p-2" >Tested</ td>
                            < td className="Dadiu p-2" >Vaccine Doses Administered</ td>
                            < td className="Dadiu p-2" >Test Positivity Ratio</ td>
                            < td className="Dadiu p-2" >Case Fatality Ratio</ td>
                            < td className="Dadiu p-2" >Recovery Ratio</ td>
                            < td className="Dadiu p-2" >Active Ratio</ td>
                            < td className="Dadiu p-2" >Population</ td>
                        </tr>
                        <tr className="state_Mizoram">
                            <td className="Mizoram p-2 table-default text-left">Mizoram</ td>
                            < td className="Mizoram p-2">Confirmed</ td>
                            < td className="Mizoram p-2">Active</ td>
                            < td className="Mizoram p-2">Recovered</ td>
                            < td className="Mizoram p-2">Deceased</ td>
                            < td className="Mizoram p-2">Other</ td>
                            < td className="Mizoram p-2">Tested</ td>
                            < td className="Mizoram p-2">Vaccine Doses Administered</ td>
                            < td className="Mizoram p-2">Test Positivity Ratio</ td>
                            < td className="Mizoram p-2">Case Fatality Ratio</ td>
                            < td className="Mizoram p-2">Recovery Ratio</ td>
                            < td className="Mizoram p-2">Active Ratio</ td>
                            < td className="Mizoram p-2">Population</ td>
                        </tr>
                        <tr className="state_AndamanNicobar">
                            <td className="AndamanNicobar p-2 table-active text-left">Andaman and Nicobar Islands</ td>
                            < td className="AndamanNicobar p-2">Confirmed</ td>
                            < td className="AndamanNicobar p-2">Active</ td>
                            < td className="AndamanNicobar p-2">Recovered</ td>
                            < td className="AndamanNicobar p-2">Deceased</ td>
                            < td className="AndamanNicobar p-2">Other</ td>
                            < td className="AndamanNicobar p-2">Tested</ td>
                            < td className="AndamanNicobar p-2">Vaccine Doses Administered</ td>
                            < td className="AndamanNicobar p-2">Test Positivity Ratio</ td>
                            < td className="AndamanNicobar p-2">Case Fatality Ratio</ td>
                            < td className="AndamanNicobar p-2">Recovery Ratio</ td>
                            < td className="AndamanNicobar p-2">Active Ratio</ td>
                            < td className="AndamanNicobar p-2">Population</ td>
                        </tr>
                        <tr className="state_Lakshadweep">
                            <td className=" Lakshadweep table-default text-left p-2">Lakshadweep</ td>
                            < td className="Lakshadweep p-2">Confirmed</ td>
                            < td className="Lakshadweep p-2">Active</ td>
                            < td className="Lakshadweep p-2">Recovered</ td>
                            < td className="Lakshadweep p-2">Deceased</ td>
                            < td className="Lakshadweep p-2">Other</ td>
                            < td className="Lakshadweep p-2">Tested</ td>
                            < td className="Lakshadweep p-2">Vaccine Doses Administered</ td>
                            < td className="Lakshadweep p-2">Test Positivity Ratio</ td>
                            < td className="Lakshadweep p-2">Case Fatality Ratio</ td>
                            < td className="Lakshadweep p-2">Recovery Ratio</ td>
                            < td className="Lakshadweep p-2">Active Ratio</ td>
                            < td className="Lakshadweep p-2">Population</ td>
                        </tr>
                        <tr className="state_India">
                            <td className="India table-active text-left p-2">India</ td>
                            < td className="India p-2">Confirmed</ td>
                            < td className="India p-2">Active</ td>
                            < td className="India p-2">Recovered</ td>
                            < td className="India p-2">Deceased</ td>
                            < td className="India p-2">Other</ td>
                            < td className="India p-2">Tested</ td>
                            < td className="India p-2">Vaccine Doses Administered</ td>
                            < td className="India p-2">Test Positivity Ratio</ td>
                            < td className="India p-2">Case Fatality Ratio</ td>
                            < td className="India p-2">Recovery Ratio</ td>
                            < td className="India p-2">Active Ratio</ td>
                            < td className="India p-2">Population</ td>
                        </tr>
                    </tbody>
                </table>
            </div>

        );
    }
}
export default Table_covid;